# Generated by Django 6.0.6 on 2026-06-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('role', models.CharField(max_length=200)),
                ('journal', models.CharField(max_length=200)),
                ('metrics', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('description', models.JSONField(default=list, help_text='JSON array of bullet-point strings, e.g. ["First point.", "Second."]')),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-year', 'title'],
            },
        ),
    ]
